[2024-07-22 13:57:35,211][flwr][INFO] - Starting Flower simulation, config: num_rounds=10, no round_timeout
[2024-07-22 13:57:37,287][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 7466293658.0, 'node:__internal_head__': 1.0, 'CPU': 12.0, 'object_store_memory': 2147483648.0, 'node:127.0.0.1': 1.0}
[2024-07-22 13:57:37,287][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-07-22 13:57:37,287][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0}
[2024-07-22 13:57:37,295][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 6 actors
[2024-07-22 13:57:37,295][flwr][INFO] - [INIT]
[2024-07-22 13:57:37,296][flwr][INFO] - Requesting initial parameters from one random client
[2024-07-22 13:57:38,895][flwr][INFO] - Received initial parameters from one random client
[2024-07-22 13:57:38,895][flwr][INFO] - Evaluating initial global parameters
[2024-07-22 13:57:41,235][flwr][INFO] - initial parameters (loss, other metrics): 181.76928067207336, {'accuracy': 0.1086, 'precision': 0.12349967530374152, 'recall': 0.1086, 'f1': 0.03553137346181725, 'confusion_matrix': array([[   0,    8,    0,  956,    0,    1,    0,   15,    0,    0],
       [   0,  122,    0, 1013,    0,    0,    0,    0,    0,    0],
       [   0,   38,    0,  971,    0,    0,    3,   19,    1,    0],
       [   0,   44,    0,  945,    1,    1,    0,   17,    2,    0],
       [   0,  143,    0,  816,    1,    0,    2,   20,    0,    0],
       [   0,  118,    0,  735,    1,    7,    0,   30,    1,    0],
       [   0,  144,    0,  749,   25,    0,    2,   38,    0,    0],
       [   0,  272,    0,  724,    8,    0,    0,    9,   15,    0],
       [   0,   81,    0,  859,    1,    0,    1,   32,    0,    0],
       [   0,  178,    0,  799,    1,    0,    0,   31,    0,    0]])}
[2024-07-22 13:57:41,236][flwr][INFO] - 
[2024-07-22 13:57:41,236][flwr][INFO] - [ROUND 1]
[2024-07-22 13:57:41,236][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 100)
[2024-07-22 13:57:47,847][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2024-07-22 13:57:47,852][flwr][WARNING] - No fit_metrics_aggregation_fn provided
[2024-07-22 13:57:50,194][flwr][INFO] - fit progress: (1, 69.25692957639694, {'accuracy': 0.7462, 'precision': 0.7800243512873444, 'recall': 0.7462, 'f1': 0.7317963218755815, 'confusion_matrix': array([[ 863,    0,    7,   18,    0,    1,   83,    3,    5,    0],
       [   0, 1103,   13,    9,    0,    0,    3,    0,    7,    0],
       [  13,   11,  831,   88,    6,    0,   48,   16,    9,   10],
       [   4,   11,   41,  876,    0,    1,    9,   27,   32,    9],
       [   0,   16,   12,    0,  579,    0,   65,    8,    4,  298],
       [  17,   37,   27,  364,   20,  229,   77,   37,   67,   17],
       [   6,    9,   15,    3,    5,    8,  910,    0,    1,    1],
       [   2,   28,   30,    3,    6,    0,    1,  926,    7,   25],
       [  13,   38,   86,  273,    4,    3,   23,   27,  451,   56],
       [  12,   15,    6,   13,   19,    0,    4,  238,    8,  694]])}, 8.958403165999998)
[2024-07-22 13:57:50,195][flwr][INFO] - configure_evaluate: no clients selected, skipping evaluation
[2024-07-22 13:57:50,195][flwr][INFO] - 
[2024-07-22 13:57:50,195][flwr][INFO] - [ROUND 2]
[2024-07-22 13:57:50,195][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 100)
[2024-07-22 13:57:55,277][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2024-07-22 13:57:57,886][flwr][INFO] - fit progress: (2, 32.586197920143604, {'accuracy': 0.8863, 'precision': 0.8864402488381707, 'recall': 0.8863, 'f1': 0.8855329269595453, 'confusion_matrix': array([[ 953,    0,    2,    2,    0,    7,   11,    1,    4,    0],
       [   0, 1099,    3,    7,    1,    1,    3,    1,   20,    0],
       [  13,    9,  888,   37,   12,    1,   25,   11,   33,    3],
       [   3,    2,   34,  889,    0,   26,    2,   17,   28,    9],
       [   0,    5,    6,    0,  903,    2,   27,    1,    5,   33],
       [  20,    5,   10,   71,   19,  707,   18,   13,   25,    4],
       [  21,    5,   10,    0,    6,   14,  901,    0,    1,    0],
       [   4,   18,   33,    1,    7,    0,    0,  915,   10,   40],
       [   9,    9,   15,   49,   14,   36,   16,    7,  804,   15],
       [  15,    6,    6,    9,  103,    6,    2,   39,   19,  804]])}, 16.650172708)
[2024-07-22 13:57:57,887][flwr][INFO] - configure_evaluate: no clients selected, skipping evaluation
[2024-07-22 13:57:57,887][flwr][INFO] - 
[2024-07-22 13:57:57,887][flwr][INFO] - [ROUND 3]
[2024-07-22 13:57:57,887][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 100)
[2024-07-22 13:58:02,174][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2024-07-22 13:58:04,581][flwr][INFO] - fit progress: (3, 27.496613178402185, {'accuracy': 0.9053, 'precision': 0.9049677006146112, 'recall': 0.9053, 'f1': 0.9049967010746114, 'confusion_matrix': array([[ 959,    0,    1,    1,    0,    7,    8,    1,    3,    0],
       [   0, 1104,   10,    3,    0,    1,    3,    1,   13,    0],
       [  14,    5,  903,   20,   20,    1,   22,   13,   27,    7],
       [   3,    1,   26,  886,    0,   44,    1,   18,   23,    8],
       [   0,    3,    5,    0,  897,    2,   14,    1,    3,   57],
       [  18,    4,    7,   38,   11,  762,   11,   11,   26,    4],
       [  13,    3,    3,    0,   17,   16,  901,    1,    4,    0],
       [   4,   14,   36,    1,    6,    0,    0,  924,    3,   40],
       [   6,    8,   13,   25,   13,   38,   16,    8,  834,   13],
       [  12,    7,    2,   10,   40,   11,    1,   34,    9,  883]])}, 23.344788458000004)
[2024-07-22 13:58:04,581][flwr][INFO] - configure_evaluate: no clients selected, skipping evaluation
[2024-07-22 13:58:04,581][flwr][INFO] - 
[2024-07-22 13:58:04,581][flwr][INFO] - [ROUND 4]
[2024-07-22 13:58:04,582][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 100)
[2024-07-22 13:58:09,598][flwr][INFO] - aggregate_fit: received 10 results and 0 failures
[2024-07-22 13:58:11,873][flwr][INFO] - fit progress: (4, 23.601183626800776, {'accuracy': 0.9109, 'precision': 0.9121988591283161, 'recall': 0.9109, 'f1': 0.9106655087628395, 'confusion_matrix': array([[ 957,    0,    2,    3,    0,    4,   10,    1,    3,    0],
       [   0, 1099,    4,    3,    1,    0,    3,    1,   24,    0],
       [  10,    3,  910,   18,   19,    1,   14,   17,   35,    5],
       [   3,    1,   19,  933,    2,    9,    1,   18,   19,    5],
       [   0,    2,    5,    0,  921,    0,   13,    0,    3,   38],
       [  16,    4,    5,   73,   18,  720,   14,    8,   28,    6],
       [  15,    3,    4,    1,   16,   12,  903,    1,    3,    0],
       [   1,   13,   27,    9,    9,    0,    0,  923,    3,   43],
       [   5,    5,    4,   42,   15,   14,    9,    5,  861,   14],
       [  10,    7,    1,   13,   64,    5,    0,   18,    9,  882]])}, 30.637581958)
[2024-07-22 13:58:11,874][flwr][INFO] - configure_evaluate: no clients selected, skipping evaluation
[2024-07-22 13:58:11,874][flwr][INFO] - 
[2024-07-22 13:58:11,874][flwr][INFO] - [ROUND 5]
[2024-07-22 13:58:11,874][flwr][INFO] - configure_fit: strategy sampled 10 clients (out of 100)
[2024-07-22 13:58:16,689][flwr][ERROR] - Traceback (most recent call last):
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TaskCancelledError): [36mray::ClientAppActor.run()[39m (pid=48749, ip=127.0.0.1, actor_id=b0d90ddbc6529138e97172ad01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x1112fbb50>)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/Users/charansr/Stamp2024/client.py", line 124, in fit
    train(self.model, trainloader, optim, epochs, self.device)
  File "/Users/charansr/Stamp2024/model.py", line 44, in train
    for images, labels in trainloader:
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1318, in _next_data
    self._shutdown_workers()
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
ray.exceptions.TaskCancelledError: Task: TaskID(1a27aa52ab666c73b0d90ddbc6529138e97172ad01000000) was cancelled.

[2024-07-22 13:58:16,689][flwr][ERROR] - Traceback (most recent call last):
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TaskCancelledError): [36mray::ClientAppActor.run()[39m (pid=48754, ip=127.0.0.1, actor_id=d9b3862cb02a086783c62cdf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x1190fbaf0>)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/Users/charansr/Stamp2024/client.py", line 124, in fit
    train(self.model, trainloader, optim, epochs, self.device)
  File "/Users/charansr/Stamp2024/model.py", line 44, in train
    for images, labels in trainloader:
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1318, in _next_data
    self._shutdown_workers()
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
ray.exceptions.TaskCancelledError: Task: TaskID(61dd0b9e9e12fd59d9b3862cb02a086783c62cdf01000000) was cancelled.

[2024-07-22 13:58:16,689][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=48749, ip=127.0.0.1, actor_id=b0d90ddbc6529138e97172ad01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x1112fbb50>)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/Users/charansr/Stamp2024/client.py", line 124, in fit
    train(self.model, trainloader, optim, epochs, self.device)
  File "/Users/charansr/Stamp2024/model.py", line 44, in train
    for images, labels in trainloader:
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1318, in _next_data
    self._shutdown_workers()
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
ray.exceptions.TaskCancelledError: Task: TaskID(1a27aa52ab666c73b0d90ddbc6529138e97172ad01000000) was cancelled.
[2024-07-22 13:58:16,689][flwr][ERROR] - [36mray::ClientAppActor.run()[39m (pid=48754, ip=127.0.0.1, actor_id=d9b3862cb02a086783c62cdf01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x1190fbaf0>)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 58, in run
    out_message = app(message=message, context=context)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/Users/charansr/Stamp2024/client.py", line 124, in fit
    train(self.model, trainloader, optim, epochs, self.device)
  File "/Users/charansr/Stamp2024/model.py", line 44, in train
    for images, labels in trainloader:
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1318, in _next_data
    self._shutdown_workers()
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/anaconda3/envs/flwr_env/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
ray.exceptions.TaskCancelledError: Task: TaskID(61dd0b9e9e12fd59d9b3862cb02a086783c62cdf01000000) was cancelled.
